# Generated by Django 3.1.5 on 2021-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Город')),
                ('Date_Time', models.DateField(verbose_name='Дата')),
                ('Temperature', models.FloatField(verbose_name='Температура')),
                ('Temperature_Min', models.FloatField(verbose_name='Температура минимальная')),
                ('Temperature_Max', models.FloatField(verbose_name='Температура максимальная')),
                ('Wind_Speed', models.FloatField(max_length=10, verbose_name='Скорость ветра')),
                ('Wind_Direction', models.FloatField(max_length=10, verbose_name='Направление ветра')),
                ('Precipitation', models.FloatField(max_length=10, verbose_name='Осадки')),
                ('Weather_Type', models.TextField(verbose_name='Тип погоды')),
                ('Conditions', models.TextField(verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
